def q(category, text, difficulty="Medium", priority=0):
    return {
        "category": category,
        "question": text,
        "difficulty": difficulty,
        "priority": priority,
    }

QUESTIONS = []

DATA = {
"Generative AI / LLM fundamentals": [
"What is an LLM, and how does it work?",
"What is a Transformer architecture?",
"Explain attention and self-attention.",
"What are tokens, embeddings and context windows?",
"What is the difference between GPT, Llama and Claude?",
"What is temperature? What happens when you increase it?",
"What are hallucinations and how can you reduce them?",
"What is prompt engineering?",
"What is zero-shot vs few-shot prompting?",
"What is function/tool calling?",
],
"RAG": [
"What is Retrieval-Augmented Generation (RAG)?",
"Why use RAG instead of fine-tuning?",
"Explain the complete RAG architecture.",
"What are embeddings?",
"How does a vector database work?",
"What is cosine similarity?",
"How do you choose chunk size?",
"What is chunk overlap?",
"How would you improve poor retrieval results?",
"What is hybrid search?",
"What are metadata filters?",
"How would you prevent an LLM from answering using irrelevant documents?",
"How do you evaluate a RAG system?",
"What are precision, recall and MRR in retrieval?",
"How would you build a RAG system for 10 million documents?",
],
"AI agents": [
"What is an AI agent?",
"Agent vs chatbot — what's the difference?",
"What is tool/function calling?",
"What is an agent orchestration framework?",
"How would you design an agent that can search documents, call APIs, query SQL and generate a report?",
"How do you prevent an agent from executing dangerous actions?",
"What is agent memory?",
"How would you handle multi-agent communication?",
"What is MCP and why is it useful?",
"How would you connect an AI agent to an enterprise application?",
],
"AI system architecture": [
"Design an enterprise GenAI platform.",
"How would you build an AI-powered customer-support system?",
"Design a document intelligence system.",
"Design an AI coding assistant.",
"Design an enterprise knowledge chatbot.",
"How would you handle millions of users?",
"How would you reduce LLM latency?",
"How would you reduce LLM cost?",
"How would you implement caching?",
"How would you monitor an LLM application?",
"What metrics would you track?",
"How do you handle failures from an LLM provider?",
"How would you design multi-model fallback?",
],
"Azure AI / Cloud": [
"How would you build RAG using Azure OpenAI + Azure AI Search?",
"Azure OpenAI vs OpenAI API?",
"How would you secure an enterprise LLM application?",
"How would you use Managed Identity?",
"How would you implement Azure AI Search vector search?",
"How would you store documents in Blob Storage and index them?",
"How would you monitor an AI application using Azure?",
"How would you implement CI/CD for an AI application?",
],
"Python / AI coding": [
"Write Python code to generate embeddings.",
"Implement cosine similarity.",
"Build a simple RAG pipeline.",
"Read PDFs and create embeddings.",
"Implement document chunking.",
"Query a vector database.",
"Build an API around an LLM using FastAPI.",
"Write code for tool/function calling.",
"Implement retry and exponential backoff for an LLM API.",
],
"ML fundamentals": [
"Supervised vs unsupervised learning?",
"Classification vs regression?",
"Overfitting vs underfitting?",
"Bias vs variance?",
"Precision vs recall?",
"F1 score?",
"ROC-AUC?",
"Cross-validation?",
"Feature engineering?",
"What is gradient descent?",
"What is a neural network?",
"CNN vs RNN vs Transformer?",
],
"Priority / Senior AI": [
"Explain Transformer architecture.",
"Explain RAG end-to-end.",
"RAG vs fine-tuning.",
"How do embeddings work?",
"How does a vector database work?",
"How do you improve RAG accuracy?",
"Design an enterprise GenAI architecture.",
"Design an AI agent with tools.",
"Explain function calling.",
"Explain MCP.",
"How do you secure an LLM application?",
"How do you reduce LLM cost and latency?",
"How do you evaluate an LLM/RAG application?",
"Build an Azure OpenAI + Azure AI Search solution.",
"Design an AI application using Python + FastAPI + vector DB + LLM.",
"Whiteboard: PDF → Blob Storage → extraction → chunking → embeddings → vector DB → retriever → RAG → LLM → response.",
]
}

for category, items in DATA.items():
    for text in items:
        QUESTIONS.append(q(
            category,
            text,
            "Hard" if category == "Priority / Senior AI" else "Medium",
            10 if category == "Priority / Senior AI" else 0
        ))
